spring.datasource.url=jdbc:postgresql://localhost:5432/tucitaidealapi
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=scarocca@gmail.com
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.ai.openai.api-key=${OPENAI_API_KEY}
cloudinary.cloud_name=dhjmvbwck
cloudinary.api_key=667616231936169
cloudinary.api_secret=O4IXeB9kyfudcyRoY05ykMvYqp0